vich_uploader:
    db_driver: orm

    mappings:
        apk:
            uri_prefix: /apk/extensions
            upload_destination: '%kernel.project_dir%/public/apk/extensions'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
